name: Setup
description: "Setup PHP and composer and install dependencies"

inputs:
  php-version:
    default: "8.3"
  coverage:
    default: xdebug
  composer-flags:
    default: ""

runs:
  using: "composite"
  steps:
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        coverage: ${{ inputs.coverage }}

    - name: Get composer cache directory
      id: composer-cache
      shell: bash
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install dependencies
      shell: bash
      run: composer update --prefer-dist --no-interaction ${{ inputs.composer-flags }}
